# Generated by Django 4.0.6 on 2022-07-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='secc_alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_respuesta_alt', models.PositiveSmallIntegerField(default=1)),
                ('alternativa', models.CharField(blank=True, max_length=100)),
                ('alternativa_respuesta', models.CharField(blank=True, max_length=100)),
                ('descripcion_breve', models.CharField(blank=True, max_length=400)),
                ('url_info', models.URLField(blank=True)),
                ('imagen_con_patologia', models.ImageField(upload_to='estudio/images/')),
                ('pregunta', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
