# Generated by Django 4.0.6 on 2022-07-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alternativas', '0002_rename_alternativa_secc_alternativa_alternativa_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secc_alternativa',
            old_name='url_info',
            new_name='url_info_esp',
        ),
        migrations.AddField(
            model_name='secc_alternativa',
            name='url_info_ing',
            field=models.URLField(blank=True),
        ),
    ]
