# Generated by Django 4.0.6 on 2022-07-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alternativas', '0003_rename_url_info_secc_alternativa_url_info_esp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secc_alternativa',
            name='descripcion_breve',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
