# Generated by Django 4.0.6 on 2022-08-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alternativas_tp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_respuesta_alt', models.PositiveSmallIntegerField(default=1)),
                ('parte_1a', models.CharField(blank=True, max_length=100)),
                ('parte_2a', models.CharField(blank=True, max_length=100)),
                ('parte_3a', models.CharField(blank=True, max_length=100)),
                ('parte_4a', models.CharField(blank=True, max_length=100)),
                ('parte_5a', models.CharField(blank=True, max_length=100)),
                ('parte_1b', models.CharField(blank=True, max_length=100)),
                ('parte_2b', models.CharField(blank=True, max_length=100)),
                ('parte_3b', models.CharField(blank=True, max_length=100)),
                ('parte_4b', models.CharField(blank=True, max_length=100)),
                ('parte_5b', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
