# Generated by Django 4.0.6 on 2022-08-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alternativas_tp',
            old_name='parte_4a',
            new_name='respuesta_a',
        ),
        migrations.RenameField(
            model_name='alternativas_tp',
            old_name='parte_4b',
            new_name='respuesta_b',
        ),
        migrations.RemoveField(
            model_name='alternativas_tp',
            name='parte_5a',
        ),
        migrations.RemoveField(
            model_name='alternativas_tp',
            name='parte_5b',
        ),
    ]
